[[plugin]]
id = "fluxaxoti/twintaillauncher-provider"
name = "TwintailLauncher Provider"
version = "1.0.1"
author = "fluxaxoti"
license = "MIT"
icon = "folder"
plugin_api = 3
deprecated = false
description = "A way to launch gacha games from TwintailLauncher through Noctalia."
tags = ["gaming", "launcher"]
